//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entertainmentPlace
    {
        public decimal entertainmentPlaceID { get; set; }
        public string entName { get; set; }
        public string entAddress { get; set; }
        public string entDescr { get; set; }
        public Nullable<decimal> entTypeID { get; set; }
        public Nullable<decimal> GovermentID { get; set; }
    
        public virtual entertainType entertainType { get; set; }
        public virtual Government Government { get; set; }
    }
}
