//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tourOffer()
        {
            this.userTourReservations = new HashSet<userTourReservation>();
        }
    
        public decimal OfferID { get; set; }
        public string PlaceDescr { get; set; }
        public string offerDescr { get; set; }
        public Nullable<decimal> CompanyID { get; set; }
        public Nullable<decimal> GovernID { get; set; }
    
        public virtual Government Government { get; set; }
        public virtual TourCompany TourCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userTourReservation> userTourReservations { get; set; }
    }
}
