//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTourReservation
    {
        public decimal userTourReservationID { get; set; }
        public Nullable<decimal> userID { get; set; }
        public Nullable<decimal> TourID { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public Nullable<decimal> numberOfPersons { get; set; }
        public Nullable<decimal> isConfirmend { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual tourOffer tourOffer { get; set; }
    }
}
