//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userCarReservation
    {
        public decimal userCarReservationID { get; set; }
        public Nullable<decimal> carofferID { get; set; }
        public Nullable<System.DateTime> datefrom { get; set; }
        public Nullable<System.DateTime> dateto { get; set; }
        public Nullable<decimal> isConfirmed { get; set; }
        public Nullable<decimal> userID { get; set; }
    
        public virtual caroffer caroffer { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
